name: Deploy Lambda and API

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-south-1

      - name: Deploy CloudFormation stack (infra only)
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yaml \
            --stack-name SmartCommStack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Wait for Lambda to be available
        run: |
          echo "Waiting for Lambda functions to be created..."
          aws lambda get-function --function-name new-smartcomm-check-status
          aws lambda get-function --function-name new-smartcomm-doc-generator

      - name: Zip and update CheckStatus Lambda
        run: |
          zip -j checkstatus.zip lambda/new-smartcomm-check-status/index.py
          aws lambda update-function-code \
            --function-name new-smartcomm-check-status \
            --zip-file fileb://checkstatus.zip

      - name: Zip and update GenerateDoc Lambda
        run: |
          zip -j generatedoc.zip lambda/new-smartcomm-doc-generator/index.py
          aws lambda update-function-code \
            --function-name new-smartcomm-doc-generator \
            --zip-file fileb://generatedoc.zip
