name: Deploy Lambda and API

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-south-1

      # Package Lambda functions and upload to S3
      - name: Package Lambda functions
        run: |
          mkdir -p build
          zip -j build/checkstatus.zip lambda/new-smartcomm-check-status/*.py
          zip -j build/generatedoc.zip lambda/new-smartcomm-doc-generator/*.py
          aws s3 cp build/checkstatus.zip s3://smartcommengines3/checkstatus.zip --region ap-south-1
          aws s3 cp build/generatedoc.zip s3://smartcommengines3/generatedoc.zip --region ap-south-1

      # Deploy CloudFormation stack (now code comes from S3)
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yaml \
            --stack-name SmartCommStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ap-south-1
          echo "Deployment completed successfully."